name: Test build and publish Escher-legacy to PyPI
on:
  workflow_dispatch:

  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - master
      - feat/publish

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 3.8, 3.9 , 3.10 ]
    runs-on: ${{ matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: Install JavaScript dependencies
        run: npm install
      - name: Build JavaScript package
        run: npm run build
      - name: Copy Package to py directory
        run: npm run copy
      - run: cd py
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -e py

  build-publish:
    needs: [test]
    name: Build and publish the package to TestPyPI
    if: github.event.pull_request.merged == true && github.event_name != 'schedule'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build JS
      uses: actions/setup-node@v3
    - name: Install JavaScript dependencies
      run: npm install
    - name: Build JavaScript package
      run: npm run build
    - name: Copy Package to py directory
      run: npm run copy
    - run: cd py
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install twine
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Check the package
      run: twine check dist/*
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run:
        twine upload --non-interactive dist/*